### ISSUE TITLE
High CPU Usage / Freeze

### ISSUE THREAD

**Issue by littleguideboi** [hsdn/tera-guide#26] opened 2020-09-04 15:44 UTC
Hey! 
I wanted to let you know that when I use your guide, my game starts to have fps drops or freezes.  You can also see what Caali said about it. Also, I hope you can fix the issue. Cuz it's getting annoying cuz of super high cpu usage. Thanks in advance!
![image](https://user-images.githubusercontent.com/36592382/92257842-8b926900-eede-11ea-9876-117ededd706b.png)

**Comment by shindmitry** [comment] 2020-09-04 16:06
Hi, 

This guide module uses base code developed by **[Kasea ](https://github.com/tera-toolbox-mods/tera-guide)** (it's a Caali friend and author of many modules for tera-proxy) without major changes. Added only voice and text display functions by Michengs and me. Many other guide forks are based on this code and we have no confirmed information that they are causing any problems with CPU load.

You should understand that the use of any guide leads to an additional load on the CPU and reduces the FPS, because additional objects are spawned and playing voice. You can disable this features (by **guide spawnObject** and **guide voice** commands) and leaving only text messages in the chat.

You can also discuss possible problems directly with Kasea, any of his suggestions will also be gladly accepted.

Any advice and comments are appreciated. You're welcome.

**Comment by littleguideboi** [comment] 2020-09-04 17:40
![image](https://user-images.githubusercontent.com/36592382/92270485-d1572d80-eeee-11ea-9976-e26b2fcdeb20.png)

**Comment by shindmitry** [comment] 2020-09-04 17:44
I gave you only basic recommendations. There have been previously reported issues https://github.com/hsdn/tera-guide/issues/24 with timeouts and intervals (which could cause a load on CPU), but this issue has been resolved in recent updates. 

If there is any other technical problem, we will try to solve it.

**Closed** 2020-09-06 19:43 UTC
Labels: question
